# Controllers to use to reach the desired poses. They must expose a FollowJointTrajectory action interface
reach_pose:
  controllers:
    - right_arm_controller
    - left_arm_controller
    - head_controller
    - torso_controller

  poses:
    home:
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: 0.0
      arm_right_2_joint: 0.0
      arm_right_3_joint: 0.0
      arm_right_4_joint: 0.0
      arm_right_5_joint: 0.0
      arm_right_6_joint: 0.0
      arm_right_7_joint: 0.0
      arm_left_1_joint:  0.0
      arm_left_2_joint:  0.0
      arm_left_3_joint:  0.0
      arm_left_4_joint:  0.0
      arm_left_5_joint:  0.0
      arm_left_6_joint:  0.0
      arm_left_7_joint:  0.0

    squat:
      torso_1_joint:     0.0
      torso_2_joint:     -0.15
      head_1_joint:      0.0
      head_2_joint:      0.25
      arm_right_1_joint: 0.0
      arm_right_2_joint: &squat_arm_2 1.3
      arm_right_3_joint: 0.0
      arm_right_4_joint: &squat_arm_4 0.9
      arm_right_5_joint: 0.0
      arm_right_6_joint: 0.0
      arm_right_7_joint: 0.0
      arm_left_1_joint:  0.0
      arm_left_2_joint:  *squat_arm_2
      arm_left_3_joint:  0.0
      arm_left_4_joint:  *squat_arm_4
      arm_left_5_joint:  0.0
      arm_left_6_joint:  0.0
      arm_left_7_joint:  0.0

    hands_front:
      arm_right_1_joint: &hands_front_arm_1  1.2
      arm_right_2_joint: &hands_front_arm_2  0.3
      arm_right_3_joint: &hands_front_arm_3 -1.0
      arm_right_4_joint: &hands_front_arm_4  1.65
      arm_left_1_joint:  *hands_front_arm_1
      arm_left_2_joint:  *hands_front_arm_2
      arm_left_3_joint:  *hands_front_arm_3
      arm_left_4_joint:  *hands_front_arm_4

    pose_t:
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: 0.0
      arm_right_2_joint: 1.61845375085
      arm_right_3_joint: 0.0
      arm_right_4_joint: 0.0
      arm_right_5_joint: 0.0
      arm_right_6_joint: 0.0
      arm_right_7_joint: 0.0
      arm_left_1_joint:  0.0
      arm_left_2_joint:  1.63474829429
      arm_left_3_joint:  0.0
      arm_left_4_joint:  0.0
      arm_left_5_joint:  0.0
      arm_left_6_joint:  0.0
      arm_left_7_joint:  0.0

    shake_hand:
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint:   0.848440316579
      arm_right_2_joint:   0.22269794206
      arm_right_3_joint:   -0.841131311478
      arm_right_4_joint:   0.721500732896
      arm_right_5_joint: 0.5
      arm_right_6_joint: 0.0
      arm_right_7_joint: 0.0
      arm_left_1_joint:  0.0
      arm_left_2_joint:  0.0
      arm_left_3_joint:  0.0
      arm_left_4_joint:  0.0
      arm_left_5_joint:  0.0
      arm_left_6_joint:  0.0
      arm_left_7_joint:  0.0

