reach_pose:
  controllers:
    - right_arm_controller
    - left_arm_controller
    - left_leg_controller
    - right_leg_controller
    - torso_controller
  poses:
    home:
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: 0.0
      arm_right_2_joint: &home_arm_2 0.1
      arm_right_3_joint: 0.0
      arm_right_4_joint: 0.0
      arm_right_5_joint: 0.0
      arm_right_6_joint: 0.0
      arm_right_7_joint: 0.0
      arm_left_1_joint:  0.0
      arm_left_2_joint:  *home_arm_2
      arm_left_3_joint:  0.0
      arm_left_4_joint:  0.0
      arm_left_5_joint:  0.0
      arm_left_6_joint:  0.0
      arm_left_7_joint:  0.0
      leg_left_1_joint:  0.0
      leg_left_2_joint:  0.0
      leg_left_3_joint:  0.0
      leg_left_4_joint:  0.0
      leg_left_5_joint:  0.0
      leg_left_6_joint:  0.0
      leg_right_1_joint: 0.0
      leg_right_2_joint: 0.0
      leg_right_3_joint: 0.0
      leg_right_4_joint: 0.0
      leg_right_5_joint: 0.0
      leg_right_6_joint: 0.0
      hand_right_thumb_joint:  0.0
      hand_right_index_joint:  0.0
      hand_right_middle_joint: 0.0
      hand_left_thumb_joint:   0.0
      hand_left_index_joint:   0.0
      hand_left_middle_joint:  0.0

    reemb_sit1: # standard walking position
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit1_arm_1 0.0
      arm_right_2_joint: &reemb_sit1_arm_2 0.0
      arm_right_3_joint: &reemb_sit1_arm_3 0.0
      arm_right_4_joint: &reemb_sit1_arm_4 0.0
      arm_left_1_joint:  *reemb_sit1_arm_1
      arm_left_2_joint:  *reemb_sit1_arm_2
      arm_left_3_joint:  *reemb_sit1_arm_3
      arm_left_4_joint:  *reemb_sit1_arm_4
      leg_right_3_joint: &reemb_sit1_leg_3 -0.17
      leg_right_4_joint: &reemb_sit1_leg_4 0.34
      leg_right_5_joint: &reemb_sit1_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit1_leg_3
      leg_left_4_joint:  *reemb_sit1_leg_4
      leg_left_5_joint:  *reemb_sit1_leg_5

    reemb_sit2: # lowering body 1
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit2_arm_1 0.69
      arm_right_2_joint: &reemb_sit2_arm_2 0.0
      arm_right_3_joint: &reemb_sit2_arm_3 0.0
      arm_right_4_joint: &reemb_sit2_arm_4 0.34
      arm_left_1_joint:  *reemb_sit2_arm_1
      arm_left_2_joint:  *reemb_sit2_arm_2
      arm_left_3_joint:  *reemb_sit2_arm_3
      arm_left_4_joint:  *reemb_sit2_arm_4
      leg_right_3_joint: &reemb_sit2_leg_3 -0.34 #-1.35
      leg_right_4_joint: &reemb_sit2_leg_4 0.52 #0.9
      leg_right_5_joint: &reemb_sit2_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit2_leg_3
      leg_left_4_joint:  *reemb_sit2_leg_4
      leg_left_5_joint:  *reemb_sit2_leg_5

    reemb_sit3: # lowering body 2
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit3_arm_1 1.39
      arm_right_2_joint: &reemb_sit3_arm_2 0.0
      arm_right_3_joint: &reemb_sit3_arm_3 0.0
      arm_right_4_joint: &reemb_sit3_arm_4 0.34
      arm_left_1_joint:  *reemb_sit3_arm_1
      arm_left_2_joint:  *reemb_sit3_arm_2
      arm_left_3_joint:  *reemb_sit3_arm_3
      arm_left_4_joint:  *reemb_sit3_arm_4
      leg_right_3_joint: &reemb_sit3_leg_3 -1.04
      leg_right_4_joint: &reemb_sit3_leg_4 0.87
      leg_right_5_joint: &reemb_sit3_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit3_leg_3
      leg_left_4_joint:  *reemb_sit3_leg_4
      leg_left_5_joint:  *reemb_sit3_leg_5

    reemb_sit4: # sitting but leaning forward
      torso_1_joint:     0.0
      torso_2_joint:     0.2
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit4_arm_1 1.92
      arm_right_2_joint: &reemb_sit4_arm_2 0.26
      arm_right_3_joint: &reemb_sit4_arm_3 0.0
      arm_right_4_joint: &reemb_sit4_arm_4 0.54
      arm_left_1_joint:  *reemb_sit4_arm_1
      arm_left_2_joint:  *reemb_sit4_arm_2
      arm_left_3_joint:  *reemb_sit4_arm_3
      arm_left_4_joint:  *reemb_sit4_arm_4
      leg_right_3_joint: &reemb_sit4_leg_3 -1.48
      leg_right_4_joint: &reemb_sit4_leg_4 1.27
      leg_right_5_joint: &reemb_sit4_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit4_leg_3
      leg_left_4_joint:  *reemb_sit4_leg_4
      leg_left_5_joint:  *reemb_sit4_leg_5

    reemb_sit5: # sitting leaning backward
      torso_1_joint:     0.0
      torso_2_joint:     -0.1
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit5_arm_1 0.0
      arm_right_2_joint: &reemb_sit5_arm_2 0.8
      arm_right_3_joint: &reemb_sit5_arm_3 0.0
      arm_right_4_joint: &reemb_sit5_arm_4 0.54
      arm_left_1_joint:  *reemb_sit5_arm_1
      arm_left_2_joint:  *reemb_sit5_arm_2
      arm_left_3_joint:  *reemb_sit5_arm_3
      arm_left_4_joint:  *reemb_sit5_arm_4
      leg_right_3_joint: &reemb_sit5_leg_3 -1.38
      leg_right_4_joint: &reemb_sit5_leg_4 1.27
      leg_right_5_joint: &reemb_sit5_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit5_leg_3
      leg_left_4_joint:  *reemb_sit5_leg_4
      leg_left_5_joint:  *reemb_sit5_leg_5

    reemb_sit6: # standing up help
      torso_1_joint:     0.0
      torso_2_joint:     0.0
      head_1_joint:      0.0
      head_2_joint:      0.0
      arm_right_1_joint: &reemb_sit6_arm_1 1.187
      arm_right_2_joint: &reemb_sit6_arm_2 1.27
      arm_right_3_joint: &reemb_sit6_arm_3 0.0
      arm_right_4_joint: &reemb_sit6_arm_4 0.0
      arm_left_1_joint:  *reemb_sit6_arm_1
      arm_left_2_joint:  *reemb_sit6_arm_2
      arm_left_3_joint:  *reemb_sit6_arm_3
      arm_left_4_joint:  *reemb_sit6_arm_4
      leg_right_3_joint: &reemb_sit6_leg_3 0.0
      leg_right_4_joint: &reemb_sit6_leg_4 0.261
      leg_right_5_joint: &reemb_sit6_leg_5 -0.17
      leg_left_3_joint:  *reemb_sit6_leg_3
      leg_left_4_joint:  *reemb_sit6_leg_4
      leg_left_5_joint:  *reemb_sit6_leg_5
