whole_body_kinematic_controller:
  type: pal_wbc/WholeBodyControlKinematicController

  useFT: False
  useIMU: False
  dt: 0.001
  floating_base: XYZ_Quaternion
  formulation: velocity
  stack_configuration: reemc_stack_both_hands_head
  solver_type: QpReductionuEqualitiesQuadprogHeapAllocation

  use_home_posture: True

  robot_model_chains:
    [hand_left_grasping_frame,
     hand_right_grasping_frame,
     leg_left_6_link,
     leg_right_6_link,
     stereo_optical_frame]
  
  default_configuration:
    leg_left_3_joint: -0.4
    leg_right_3_joint: -0.4
    leg_left_4_joint: 0.8
    leg_right_4_joint: 0.8
    leg_left_5_joint: -0.4
    leg_right_5_joint: -0.4
    arm_left_2_joint: 0.3
    arm_right_2_joint: 0.3
    arm_left_4_joint: 0.8
    arm_right_4_joint: 0.8
    
