whole_body_kinematic_controler:
  type: wbc/WholeBodyControlKinematicStabilizerController

  left_ft_sensor: left_ft
  right_ft_sensor: right_ft
  base_imu_sensor: base_imu
  
  dt: 0.005
  floating_base: True
  formulation: velocity
  stack_configuration: reemc_ball_grasping_stack
  use_damping: True
  damp: 0.2
  
  robot_model_chains:
    [arm_left_7_link,
     arm_right_7_link,
     leg_left_6_link,
     leg_right_6_link,
     stereo_optical_frame]
  
  default_configuration:
    leg_left_3_joint: -0.4
    leg_right_3_joint: -0.4
    leg_left_4_joint: 0.8
    leg_right_4_joint: 0.8
    leg_left_5_joint: -0.4
    leg_right_5_joint: -0.4
    arm_left_2_joint: 0.3
    arm_right_2_joint: 0.3
    arm_left_4_joint: 0.8
    arm_right_4_joint: 0.8

  stabilizer:
    ds_min_weight: 300.0
    ds_x_p: 0.4
    ds_y_p: 0.4
    dead_zone: 0.01
    hip_offset_x_clamp: 0.02
    hip_offset_y_clamp: 0.04
    hip_offset_decay: 0.99

